language: java

jdk:
  - openjdk8
  - openjdk9
  - openjdk10
  - oraclejdk11

# see https://blog.travis-ci.com/2014-12-17-faster-builds-with-container-based-infrastructure
sudo: false

env:
  - secure: "GOnKWQXhSe9ksS4/mlRvXR+CB4nLTYUm5w4opz61hoeDDkASSlxKYi//5kVGL2hSke2owdDXxjaWpsjrqFHAG1JLkwtNoY/I9NfykqxZyBtXkQlksRckknMiCnfpJu6biDTLAobk6XRQv/j6LUYjtrgLNM3PrjIQxv86AmCAw4vOIEAoR0sS4z9TrIJ45nyTROLAR4RQAQ16nF7HM3b6aqhoMaio44e0vxUr1404U69uIqJRCVmbPIstlXBgD1HqpXJ3XuKJtaayvZaha+qggc5bzLr1SfywvIcRaKJp2BOUF1uZHDRZuSDns0WKBCbyPGRHl5qLjCjx51h/fL7q9daycB+1Amv+6BJXqOhHXBa4D1rMPNLcdwn34oKDNwNqbA6w0C+zpsRD4h5dpRBSX1KBIccChQRG71bigsCxH4weMikjKT0NocWSursB55Ges/onL6SzmJiPa7ibeju7ifem/F1RbZHoj4Tt+3+yNm4CHFFV/k/9PtnaV8s86HKZZHb19HFtExDtLUXAlI8E+YXPWf4RrU5M0KPSRRbmI166t4zrB6YoFJJ36rKjkSbbNghuoo+/d9d204d5R/+tm9wXAXHuPlkArjVke2d1SnFO8rXizXt0WNWZfsryG5gTli4lx8vFpV12ixPzUfibUu7S0xWz6RCZDBw0nsf+ekQ="

# cache the build tool's caches
cache:
  directories:
    - $HOME/.m2

notifications:
  slack:
    secure: aZgSQDJHiWcdE6OAuDRruTZMIHp4lzvU+1SkQcxMdQ/5UDtFaFCUOTQXLqgGhEAkmwFX00Z16u0Nf4zu8RVC8do/5yeEg3Gs11q/E8R9BEDMGqANGEpqcUTmEHdu29DKoSW7MWrNR1wpigzNYV2Tb0jcXHefIIGtezmczP5aje4Bxv9mJq2+xtIYIr0+WnByg9vFcLvh+zIatlB2se3KboQKFeZ7M8Ptvx8bzD9Qsy0W0HOdLGdccUYxM+AuK1OM0acBObNQ/I9iorjFeJ1Y2UGCXaxhhKkHtbnEbnK38lVIkQRSl8plMIn7kVT1+r/buzcFSPDflXPwYWBHsWdEaMMQet+psbTd5I0iYzoo3eE9ed1610xDyKbVnNeRiPJ+UT1bsHI4UdhhsdwfVHcn9RG2dEuChEWFmvRucl1KxUQoaTXwIiondykXzj0VqJoEtpRvoaCjtwhzhUP6ovwQiX8nRv0V8d78jTn9QNcVC1yWashQRHCTf8eeu955IQYUUk1/iyt4e/J1h9siDwA7qkOuWudvPwkvmYpkXrjeyh2xT0pcGpR6a6mIy8uqN81qU0xmiYtByj8chivsNSQi+w4IixrAD/lCipfqPwUsBp3Mec62P4sXW0LU8iQRbtUSa900+Ch450lJOMnyKL5zxmW7UIb2mpH8uOp+sPf/qVM=
    if: (tag =~ /[0-9]+\.[0-9]+\.[0-9]/) OR (branch = develop)
    template: "%{repository_name} build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) by %{author} %{result} after %{duration}"
    on_success: always
    on_failure: always